Repository commercelayer/mfe-my-account, pull requests merged in 2023-11, with the labels that each got.

#135 Update `react-components` and minor dependencies
  packages/my-account/package.json
  packages/my-account/specs/fixtures/tokenizedPage.ts
  packages/my-account/src/assets/locales/en/common.json
  packages/my-account/src/assets/locales/it/common.json
  packages/my-account/src/components/composite/Address/CustomerAddressForm/index.tsx
  packages/my-account/src/components/composite/Order/OrderAccordion/index.tsx
  packages/my-account/src/components/composite/Order/OrderDate/index.tsx
  packages/my-account/src/components/composite/Order/OrderShipments/index.tsx
  packages/my-account/src/components/composite/Order/OrderStatusChip/index.tsx
  packages/my-account/src/pages/OrdersPage/index.tsx
  packages/my-account/src/pages/OrdersPage/styled.tsx
  packages/my-account/src/utils/getOrder.ts
  packages/my-account/src/utils/getSettings.ts
  pnpm-lock.yaml
Labels: dependencies

#136 v1.2.0
  lerna.json
  packages/my-account/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#138 v1.2.1
  lerna.json
  packages/my-account/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#139 Add wallet section to docs
  packages/my-account/README.md
Labels: documentation
